In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Vipul\IMDB Dataset.csv")

In [2]:
df.head(5)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# Do Lowercasing

In [3]:
df['review'].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

# REMOVE HTML TAGS & URLs

In [4]:
import re

def remove_html_tags(text):
    clean_text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    return clean_text
    

In [5]:
df['review']=df['review'].apply(remove_html_tags)

In [6]:
import re

def remove_urls(text):
    # Regex pattern to match URLs
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    # Replace URLs with an empty string
    clean_text = url_pattern.sub('', text)
    return clean_text

# REMOVING PUNCTUATION

In [7]:
import string

punctuation = string.punctuation
print(punctuation)


!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [8]:
def remove_punctuation(text):
    
    for char in punctuation:
        text = text.replace(char,'')
    return text

In [9]:
df['review']=df['review'].apply(remove_punctuation)

In [10]:
df['review']

0        One of the other reviewers has mentioned that ...
1        A wonderful little production The filming tech...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...                        
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: object

In [11]:
# Alternate method for big data set to remove punctuation

import string

def remove_punctuation_2(text):
    # Generate translation table mapping all punctuation characters to None
    translation_table = str.maketrans('', '', string.punctuation)
    # Remove punctuation using translate() method
    clean_text = text.translate(translation_table)
    return clean_text




# CHAT WORD TREATMENT 

In [12]:
import re

def chat_word_treatment(chat_message):
    # Define a dictionary for abbreviation expansion
    abbreviations = {
        'lol': 'laughing out loud',
        'brb': 'be right back',
        'ttyl': 'talk to you later'
        # Add more abbreviations as needed
    }
    
    # Define a dictionary for slang conversion
    slang = {
        'u': 'you',
        'r': 'are',
        'gr8': 'great',
        # Add more slang terms as needed
    }
    
    # Normalize chat message to lowercase
    chat_message_lower = chat_message.lower()
    
    # Replace abbreviations while preserving capitalization
    for abbreviation, full_form in abbreviations.items():
        pattern = re.compile(r'\b' + re.escape(abbreviation) + r'\b', re.IGNORECASE)
        chat_message_lower = pattern.sub(full_form, chat_message_lower)
    
    # Replace slang terms while preserving capitalization
    for term, replacement in slang.items():
        pattern = re.compile(r'\b' + re.escape(term) + r'\b', re.IGNORECASE)
        chat_message_lower = pattern.sub(replacement, chat_message_lower)
    
    return chat_message_lower

# Example usage:
chat_message = "LOL u r gr8! brb ttyl"
processed_chat_message = chat_word_treatment(chat_message)
print(processed_chat_message)


laughing out loud you are great! be right back talk to you later


# SPELLING CORRECTION

In [13]:
from spellchecker import SpellChecker

def spell_correction_pyspellchecker(text):
    spell = SpellChecker()
    # Split text into words
    words = text.split()
    corrected_text = []
    for word in words:
        # Get the corrected version of each word
        corrected_word = spell.correction(word)
        corrected_text.append(corrected_word)
    return ' '.join(corrected_text)

# Example usage:
text = "Thes is an example of spell correction using pyspellchecker."
corrected_text_pyspellchecker = spell_correction_pyspellchecker(text)
print("Pyspellchecker Corrected Text:", corrected_text_pyspellchecker)


ModuleNotFoundError: No module named 'spellchecker'

In [ ]:
# using textblob

from textblob import TextBlob

def spell_correction_textblob(text):
    blob = TextBlob(text)
    corrected_text = blob.correct()
    return str(corrected_text)

# Example usage:
text = "Thes is an example of spell correction using TextBlob."
corrected_text_textblob = spell_correction_textblob(text)
print("TextBlob Corrected Text:", corrected_text_textblob)


#  Removing Stopword

In [14]:
import nltk


In [15]:
from nltk.corpus import stopwords

In [16]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vipul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def remove_stopwords(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Get the list of English stopwords
    stop_words = set(stopwords.words('english'))
    
    # Remove stopwords from the list of words
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Join the filtered words back into a single string
    filtered_text = ' '.join(filtered_words)
    
    return filtered_text

# Example usage:
text = "This is an example sentence demonstrating the removal of stopwords using NLTK."
filtered_text = remove_stopwords(text)
print("Filtered Text:", filtered_text)


Filtered Text: example sentence demonstrating removal stopwords using NLTK .


In [19]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Vipul\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [20]:
import re

def remove_emojis(text):
    # Define regex pattern to match emojis
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               "]+", flags=re.UNICODE)
    # Remove emojis from the text
    clean_text = emoji_pattern.sub(r'', text)
    return clean_text

# Example usage:
text_with_emojis = "Hello! 😊 This is a message with emojis! 🌟🚀"
clean_text = remove_emojis(text_with_emojis)
print("Clean Text:", clean_text)


Clean Text: Hello!  This is a message with emojis! 


# TOKENIZATION

Tokenization is the process of breaking down text into smaller units called tokens. These tokens can be words, phrases, or other meaningful elements depending on the context and the specific requirements of the task at hand. Tokenization is a fundamental preprocessing step in natural language processing (NLP). 

In [21]:
import nltk
from nltk.tokenize import word_tokenize

# Example text
text = "Tokenization is the process of breaking down text into smaller units called tokens."

# Tokenize the text into words
tokens = word_tokenize(text)

print("NLTK Word Tokenization:")
print(tokens)


NLTK Word Tokenization:
['Tokenization', 'is', 'the', 'process', 'of', 'breaking', 'down', 'text', 'into', 'smaller', 'units', 'called', 'tokens', '.']


# Using Spacy

In [22]:
import spacy



# Download the 'en_core_web_sm' model
spacy.cli.download("en_core_web_sm")


# Load spaCy English tokenizer
nlp = spacy.load("en_core_web_sm")

# Example text
text = "Tokenization is the process of breaking down text into smaller units called tokens."

# Tokenize the text using spaCy
doc = nlp(text)

# Extract tokens from spaCy document
tokens = [token.text for token in doc]

print("spaCy Tokenization:")
print(tokens)


✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
spaCy Tokenization:
['Tokenization', 'is', 'the', 'process', 'of', 'breaking', 'down', 'text', 'into', 'smaller', 'units', 'called', 'tokens', '.']


# STEMMING

Stemming is the process of reducing words to their root or base form, typically by removing suffixes or prefixes. It's a common technique used in natural language processing (NLP) and information retrieval to normalize words and reduce them to a common form.

There are various stemming algorithms available, with the Porter stemming algorithm being one of the most widely used. NLTK (Natural Language Toolkit) provides an implementation of the Porter stemming algorithm, which you can use in Python.

In [23]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

# Create a stemmer object
stemmer = PorterStemmer()

# Example text
text = "I am loving this beautiful day. It's sunny outside and I'm going for a walk."

# Tokenize the text into words
words = word_tokenize(text)

# Stem each word in the list of words
stemmed_words = [stemmer.stem(word) for word in words]

# Join the stemmed words back into a single string
stemmed_text = ' '.join(stemmed_words)

print("Original Text:")
print(text)
print("\nStemmed Text:")
print(stemmed_text)


Original Text:
I am loving this beautiful day. It's sunny outside and I'm going for a walk.

Stemmed Text:
i am love thi beauti day . it 's sunni outsid and i 'm go for a walk .


"this" was stemmed to "thi", which is also a result of the rules applied by the stemming algorithm. While "thi" is not a valid English word, stemming algorithms prioritize the reduction of words to their base form, often resulting in such transformations.

It's important to note that stemming is a crude heuristic process and may not always produce meaningful or correct results, especially for irregular words or words with complex morphology. In some cases, more advanced techniques like lemmatization, which considers the morphological analysis of words, may be preferred over stemming.

# LEMMITIZATION

In [25]:
import nltk
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Vipul\AppData\Roaming\nltk_data...


True

In [29]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Create a lemmatizer object
lemmatizer = WordNetLemmatizer()

# Example text
text = "I am loving this beautiful day. It's sunny outside and I'm going for a walk."

# Tokenize the text into words
words = word_tokenize(text)

# Lemmatize each word in the list of words
lemmatized_words = [lemmatizer.lemmatize(word,pos='v') for word in words]

# Join the lemmatized words back into a single string
lemmatized_text = ' '.join(lemmatized_words)

print("Original Text:")
print(text)
print("\nLemmatized Text:")
print(lemmatized_text)


Original Text:
I am loving this beautiful day. It's sunny outside and I'm going for a walk.

Lemmatized Text:
I be love this beautiful day . It 's sunny outside and I 'm go for a walk .


Stemming is fast. Lemmitization is slow, if output has to be shown to user use Lemmitization.

https://www.kaggle.com/code/sudalairajkumar/getting-started-with-text-preprocessing

#  TEXT REPRESENTATION

In [30]:
 #Bag of words & N-grams
    
from sklearn.feature_extraction.text import CountVectorizer

# Example text data
corpus = [
    "The quick brown fox jumps over the lazy dog",
    "I love to eat pizza with extra cheese",
    "Machine learning is an exciting field of study"
]

# Bag of Words (BoW)
def bow_representation(corpus):
    # Create CountVectorizer object
    vectorizer = CountVectorizer()

    # Fit and transform the corpus to create BoW representation
    bow_matrix = vectorizer.fit_transform(corpus)

    # Get the vocabulary (unique words) from the CountVectorizer
    vocabulary = vectorizer.get_feature_names_out()

    # Convert BoW matrix to array and return with vocabulary
    return bow_matrix.toarray(), vocabulary

bow_matrix, vocabulary = bow_representation(corpus)
print("Bag of Words (BoW) Matrix:")
print(bow_matrix)
print("Vocabulary:")
print(vocabulary)
print()

# N-grams
def ngram_representation(corpus, n):
    # Create CountVectorizer object with specified n-gram range
    vectorizer = CountVectorizer(ngram_range=(n, n))

    # Fit and transform the corpus to create n-gram representation
    ngram_matrix = vectorizer.fit_transform(corpus)

    # Get the vocabulary (unique n-grams) from the CountVectorizer
    ngram_vocabulary = vectorizer.get_feature_names_out()

    # Convert n-gram matrix to array and return with n-gram vocabulary
    return ngram_matrix.toarray(), ngram_vocabulary

# Example usage for bigrams (2-grams)
ngram_matrix, ngram_vocabulary = ngram_representation(corpus, n=2)
print("Bigrams (2-grams) Matrix:")
print(ngram_matrix)
print("Bigrams Vocabulary:")
print(ngram_vocabulary)


Bag of Words (BoW) Matrix:
[[0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 2 0 0]
 [0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1]
 [1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0]]
Vocabulary:
['an' 'brown' 'cheese' 'dog' 'eat' 'exciting' 'extra' 'field' 'fox' 'is'
 'jumps' 'lazy' 'learning' 'love' 'machine' 'of' 'over' 'pizza' 'quick'
 'study' 'the' 'to' 'with']

Bigrams (2-grams) Matrix:
[[0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0]
 [0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1]
 [1 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0]]
Bigrams Vocabulary:
['an exciting' 'brown fox' 'eat pizza' 'exciting field' 'extra cheese'
 'field of' 'fox jumps' 'is an' 'jumps over' 'lazy dog' 'learning is'
 'love to' 'machine learning' 'of study' 'over the' 'pizza with'
 'quick brown' 'the lazy' 'the quick' 'to eat' 'with extra']


Drawbacks of Bag of Words (BoW):

    Loss of word order and context

    High dimensionality

    Out-of-vocabulary words

    Difficulty handling polysemy and synonymy

    Fixed-length representation

    Lack of semantic information


Drawbacks of n-grams:

    Increased Dimensionality
    Data Sparsity
    Lack of Generalization
    Increased Memory Usage

# TF-IDF

TF-IDF (Term Frequency-Inverse Document Frequency) is a numerical statistic used in natural language processing (NLP) and information retrieval to measure the importance of a term (word) in a document relative to a corpus of documents. It combines two metrics: term frequency (TF) and inverse document frequency (IDF).

Term Frequency (TF): TF measures the frequency of a term (word) in a document. It is calculated as the ratio of the number of times a term appears in a document to the total number of terms in the document. TF gives higher weight to terms that appear more frequently in the document.

Inverse Document Frequency (IDF): IDF measures the rarity of a term across the entire corpus of documents. It is calculated as the logarithm of the ratio of the total number of documents in the corpus to the number of documents containing the term. IDF gives higher weight to terms that are rare across the corpus, as they are more discriminative.

TF-IDF Score: The TF-IDF score of a term in a document is the product of its TF and IDF scores. It indicates how important the term is in the document relative to the entire corpus. Terms with higher TF-IDF scores are considered more important and are often used as features in tasks such as text classification, information retrieval, and document similarity.

In summary, TF-IDF assigns higher weights to terms that are frequent in the document but rare across the corpus, making it a useful metric for capturing the discriminative power of terms in text data.





In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample documents
documents = [
    "The quick brown fox jumps over the lazy dog",
    "The dog",
    "The fox is quick"
]

# Initialize TF-IDF Vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer to the documents and transform the documents into TF-IDF vectors
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

# Print feature names (words)
print("Feature names:", tfidf_vectorizer.get_feature_names_out())

# Print TF-IDF matrix
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())


Feature names: ['brown' 'dog' 'fox' 'is' 'jumps' 'lazy' 'over' 'quick' 'the']
TF-IDF Matrix:
 [[0.3744896  0.284809   0.284809   0.         0.3744896  0.3744896
  0.3744896  0.284809   0.44235919]
 [0.         0.78980693 0.         0.         0.         0.
  0.         0.         0.61335554]
 [0.         0.         0.4804584  0.63174505 0.         0.
  0.         0.4804584  0.37311881]]


# Word2vec


Word2Vec is a popular technique in natural language processing (NLP) for learning distributed representations of words in a vector space. It maps words to continuous vector representations, capturing semantic similarities between words. There are two main types of Word2Vec models:

Continuous Bag of Words (CBOW):

    CBOW predicts the target word given its context (surrounding words within a fixed window).
    
    Use CBOW when you have a large dataset and you're more concerned about the speed of training. It's faster to train than 
    skipgram.
    
    Works well with frequent words.
    
Skip-gram:

    Skip-gram predicts the context words given a target word.
    Use Skip-gram when you have a small dataset or want to capture rare words and their relationships better.
    Captures more information about infrequent words and phrases.
    When to use each type depends on your specific task and data characteristics:

If you have a large dataset and you're more concerned about training speed, CBOW might be a better choice.

If you have a small dataset or you want to capture better relationships between rare words, Skip-gram might be more suitable.

Skip-gram tends to perform better with large datasets and is more robust for infrequent words and phrases.

CBOW is faster to train and often performs better for frequent words.

In practice, it's often a good idea to try both CBOW and Skip-gram on your dataset and evaluate which one works better for your specific task. Additionally, pre-trained Word2Vec models are available for various languages and domains, which can be fine-tuned or used directly for downstream tasks such as sentiment analysis, named entity recognition, and machine translation.








In [3]:
import numpy as np
import pandas as pd
import gensim
import os

In [4]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for filename in os.listdir('data'):
    
    f = open(os.path.join('data',filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [5]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [6]:
model.build_vocab(story)

In [7]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6569794, 8628190)

In [8]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8133265376091003),
 ('targaryen', 0.7668876051902771),
 ('unburnt', 0.7458482980728149),
 ('myrcella', 0.736862301826477),
 ('princess', 0.7245938777923584),
 ('queen', 0.7145258188247681),
 ('rhaegar', 0.6532346606254578),
 ('elia', 0.64824378490448),
 ('margaery', 0.6471149325370789),
 ('dorne', 0.6423312425613403)]

In [9]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [10]:
model.wv.doesnt_match(['cersei', 'jaime', 'bronn', 'tyrion'])

'bronn'

In [11]:
model.wv.similarity('arya','sansa')

0.8409555

In [12]:
y = model.wv.index_to_key

In [13]:
#reducing the dimension using PCA
from sklearn.decomposition import PCA

In [14]:
pca = PCA(n_components=3)
X = pca.fit_transform(model.wv.get_normed_vectors())
X.shape

(17453, 3)

Bag of Words (BoW):

Use Case: Bag of Words is commonly used for text classification tasks where word order is not important, such as sentiment analysis or spam detection.

Example: Suppose you're building a sentiment analysis system to classify movie reviews as positive or negative. You can represent each review as a bag of words, ignoring word order but capturing word frequencies.

N-grams:

Use Case: N-grams are useful when you want to capture local word order and context, such as in language modeling or machine translation.

Example: In a language modeling task, you might use trigrams (3-grams) to predict the next word in a sentence based on the two preceding words. For instance, given the phrase "the quick brown," you can predict the next word by considering trigrams like ("the", "quick", "brown").

TF-IDF (Term Frequency-Inverse Document Frequency):

Use Case: TF-IDF is effective for information retrieval tasks where you want to weigh the importance of words in documents based on their frequency and rarity across a corpus.

Example: Consider a search engine where you want to retrieve relevant documents for a user query. TF-IDF helps identify documents containing rare words (which might be more informative) while penalizing common words.

Word2Vec:

Use Case: Word2Vec is ideal when you need to capture semantic relationships between words and represent them in a continuous vector space. It's often used for tasks like similarity detection, document clustering, or word analogy tasks.

Example: In a document clustering task, you can use Word2Vec to represent each document as a vector and then cluster similar documents together based on the similarity of their vector representations.

Each technique has its strengths and weaknesses, and the choice depends on the specific requirements of your task. For instance, if you need to capture word order and context, n-grams might be more suitable than bag of words. If you're interested in capturing semantic similarities between words, Word2Vec would be a better choice than TF-IDF. Understanding the characteristics and applicability of each technique will help you choose the most appropriate one for your NLP task.

GloVe, FastText, Doc2Vec, BERT, Transformer Models